[package]
name = "image-cooking"
version = "0.0.2"
edition = "2024"
description = "A CLI tool to compress images"
license = "MIT" 
repository = "https://github.com/xiaoFeng5210/image-cooking"
readme = "README.md"
keywords = ["image", "compress", "cli"]
categories = ["command-line-utilities"]



[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
image = "0.25.10"
